#pragma once
#include <iostream>
#include <curses.h>
#include <vector>
#include <numeric>
#include <cmath>
#include <string>
#include <functional>
#include <optional>
#include <map>
#include <algorithm>
#include <variant>
#include <array>
